[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
dynamic = ["version"]
description = "Core maze generation module from A-MAZE-ING pipeline"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Tu Nombre / 42 Login", email = "tu_email@student.42.fr" },
    { name = "Tu Nombre / 42 Login", email = "tu_email@student.42.fr" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic>=2.0.0"
]

[tool.setuptools.dynamic]
version = { attr = "src.mazegen.generator.__version__" }

[tool.setuptools]
package_dir = { "" = "src" }
packages = ["mazegen"]

[tool.mypy]
strict = true
mypy_path = "typings"
exclude = [
    "\\.venv",
    "\\.mypy_cache",
    "\\.pytest_cache",
    "build",
    "dist"
]