class Playback:
    active: bool

    def __init__(self) -> None: ...
    def load_file(self, file_path: str) -> None: ...
    def play(self) -> None: ...
    def stop(self) -> None: ...
    def loop_at_end(self, loop: bool) -> None: ...
